/*
 * Tiku Operating System
 * http://tiku-os.org
 *
 * tiku_kits_gfx_font_dejavu14b.h - Auto-generated bitmap font
 *
 * Source font  : DejaVuSansMono-Bold.ttf
 * Size         : 14 pt -> 17 px (13 ascent + 4 descent)
 * Range        : 0x20 .. 0x7E  (95 glyphs)
 * Layout       : monospace
 * Glyph data   : 2280 bytes
 * Generated by : tools/font_bake.py at 2026-05-03 00:34:07
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef TIKU_KITS_GFX_FONT_DEJAVU14B_H_
#define TIKU_KITS_GFX_FONT_DEJAVU14B_H_

#include "../tiku_kits_gfx_text.h"

extern const tiku_kits_gfx_font_t tiku_kits_gfx_font_dejavu14b;

#endif /* TIKU_KITS_GFX_FONT_DEJAVU14B_H_ */
