/*
 * Tiku Operating System
 * http://tiku-os.org
 *
 * tiku_kits_gfx_font_dejavu10.h - Auto-generated bitmap font
 *
 * Source font  : DejaVuSansMono.ttf
 * Size         : 10 pt -> 13 px (10 ascent + 3 descent)
 * Range        : 0x20 .. 0x7E  (95 glyphs)
 * Layout       : monospace
 * Glyph data   : 1140 bytes
 * Generated by : tools/font_bake.py at 2026-05-03 00:34:06
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef TIKU_KITS_GFX_FONT_DEJAVU10_H_
#define TIKU_KITS_GFX_FONT_DEJAVU10_H_

#include "../tiku_kits_gfx_text.h"

extern const tiku_kits_gfx_font_t tiku_kits_gfx_font_dejavu10;

#endif /* TIKU_KITS_GFX_FONT_DEJAVU10_H_ */
